name: Trigger Fedify Sponsors Update
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  trigger-sponsors:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger sponsors workflow in main repo
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}" \
          -H "User-Agent: automation-trigger" \
          https://api.github.com/repos/fedify-dev/fedify/actions/workflows/sponsors.yaml/dispatches \
          -d '{"ref":"main"}'